    
file_test = File()
print(len(file_test))
file_test.estVide()
file_test.ajouterFile('A')
file_test.ajouterFile('B')
file_test.ajouterFile('C')
file_test.ajouterFile('D')
print(len(file_test))
print(file_test.estVide())
print(file_test.valeurTete())
print(file_test.retirerFile())
print(file_test.valeurTete())
print(len(file_test))
